#!/bin/sh

if [[ "$(git config --get my.interactive)" = yes ]];then
    # git -c my.interactive=yes commit
    exec < /dev/tty yarn ts-node -r tsconfig-paths/register app/cui/commands commit --hook
fi
